### ISSUE TITLE
Bind Commands to Events and Queries to Results in Handlers

### ISSUE THREAD

**Issue by JamesYopp** [reactific/riddl#232]
One downfall of the "..." syntax for handlers is you would be able to detect on command usages of commands, but event usage is hidden, for example, `and "yield SomethingImportantHappened event"`
Should we consider requiring every command handler to have a yield statement - even if it is `yield nothing`. I am not sure that we need to populate all fields of the event - just declare that we are yielding that event.
Likewise do we require queries to yield a result?
I am thinking making at least this connection would ensure that uses evaluations as part of the RIDDL evaluations were more complete.

**Comment by reid-spencer** [comment]
This has been solved with the introduction of streaming features in RIDDL. The yield statement is no longer supported because it was designed to yield back to only the invoker. Design wise that is short sighted. What should be done is to send the event to a stream.  The validator should missing warnig when a command handler doesn't generate an event.

**Comment by reid-spencer** [comment]
This has now been implemented with this commit:
https://github.com/reactific/riddl/commit/374bc3efd2625001526536b2ae3b8f9d1de49eb8
