### ISSUE TITLE
Allow for empty messages

### ISSUE THREAD

**Issue by AlexWeinstein92** [reactific/riddl#448]
An empty message now begs for a field or `???`, neither of which seem suitable for representing messages with no fields

<img width="428" alt="Screenshot 2023-09-29 at 2 52 11 PM" src="https://github.com/reactific/riddl/assets/105220856/78a16dad-c2c0-46cd-afa7-0aeda381ca5f">

**Comment by reid-spencer** [comment]
The ??? thingis used just like it is in Scala: Unimplemented Feature and a legitimate way to get a rough set of definitions in without worrying about the details. 

Empty messages were purposefully removed because they were causing validation to fail. Given the parser technology I'm using there isn't an alternative.  So, suck it. up and type 3 question marks if you don't want to write  definition.
