### ISSUE TITLE
multiple issues with output declarations

### ISSUE THREAD

**Issue by JamesYopp** [reactific/riddl#486]
`page PricingPage {
  output PricingPageText showsksoTemplateApp. ProductOfferingText
  ...
}`

This should not compile. First, there should be a space between shows and ksoTemplateApp. Second, there should be a record keyword between shows and ksoTemplateApp. Third, there should not be a space between ksoTemplateApp. and ProductOfferingText. The correct syntax would be:

`page PricingPage{
  output PricingPageText shows record ksoTempateApp.ProductOfferingText
  ...
}`

**Comment by reid-spencer** [comment]
I will try to get to this tomorrow

**Comment by reid-spencer** [comment]
It turns out this syntax is actually legal.  I reformatted the AST, and for the output element it yielded:
`output PricingPageText shows type ksoTemplateApp.ProductOfferingText`. This shows that it differentiated the shows keyword and accepted the type name without the keyword.  The only surprising part there is that the keyword did not require space after it.  This is a general problem throughout the language and needs to be fixed everywhere. Big job.
